### ISSUE TITLE
Пожелания для почты

### ISSUE THREAD

**Issue by Darimark** [AlexVin-Dev/Yukon_Union#13]
Предложение от сотрудников компании.
- [x] 1. В почте напротив каждого нового письма добавить чек бокс с выделением группы писем для их  удаления.
- [X] 2. Добавить функцию  "прочитать все".
- [X] 3. При почтении сообщения и перемещения его в архив, перемещало либо на весь список сообщений либо на следующее .

**Comment by AlexVin-Dev** [comment]
Я учту вашу идею.

**Comment by AlexVin-Dev** [comment]
3. Готово

**Comment by AlexVin-Dev** [comment]
> 2\. Добавить функцию  "прочитать все".
Готово, а также исправлена система счетчика.
