### ISSUE TITLE
Новая система уведомление.

### ISSUE THREAD

**Issue by AlexVin-Dev** [AlexVin-Dev/Yukon_Union#6]
Переписать полностью систему уведомление в новый формат сообщений. 

- [ ] Изменить статус прочтение со status на read
- [ ] Добавить возможность отвечать на сообщения.
- [x] Добавить возможность для администрации увидеть прочитано сообщение или нет. 
- [ ] При создание новостей отправлять не определенному пользователю, а функция всем. 
- [ ] Добавить возможность написать личное сообщение игроку.

**Comment by AlexVin-Dev** [comment]
Созданы страницы: 
-  Список всех уведомлений.
-  Просмотр уведомление.

**Comment by AlexVin-Dev** [comment]
Новости теперь приходят в сообщение.

**Comment by AlexVin-Dev** [comment]
Добавлена возможность добавлять сообщение в избранное и при желание удалять из избранного.
При открытие определённого сообщение сообщение автоматически прочитаете, как - это делается в письмах.

**Comment by AlexVin-Dev** [comment]
Заказ аватарок, отклонённые и принятые заявка на авы теперь приходят на почту.

**Comment by AlexVin-Dev** [comment]
Добавлена возможность отправлять письма в архив.

**Comment by AlexVin-Dev** [comment]
**Полностью переделаны системы уведомлений на сообщение.**
- Принятие, отклонение, рейсов.
- Принятие, отклонение отпуска.

**Comment by gorechaser** [comment]
> Новости теперь приходят в сообщение.

При открытии единственного сообщения счётчик уведомлений всё равно показывает что есть новое сообщение пока не загрузишь след страницу или обновишь.

**Comment by AlexVin-Dev** [comment]
> > Новости теперь приходят в сообщение.
> 
> При открытии единственного сообщения счётчик уведомлений всё равно показывает что есть новое сообщение пока не загрузишь след страницу или обновишь. 

Не вижу в этом проблемы, но я пересмотрю, что можно сделать.

**Comment by AlexVin-Dev** [comment]
Добавлена рабочая система подтверждения для Экспедитора.

**Comment by AlexVin-Dev** [comment]
Исправлена система прочтение чужих сообщений.

**Comment by AlexVin-Dev** [comment]
Добавлено отображение кому пришло сообщение.

**Comment by AlexVin-Dev** [comment]
Если в уведомлениях о сообщений больше 3, то появиться scroll

**Comment by AlexVin-Dev** [comment]
По просьбам участников компании. Верну систему уведомлений о принятие ваших рейсов, как было раньше. Если ваш рейс отклонили или вернули будет отправляться в сообщения. В будущем вы сможете на данные сообщение отвечать.
